try this huinia on prod 3

diff --git a/.github/workflows/infra-deploy.yml b/.github/workflows/infra-deploy.yml
--- a/.github/workflows/infra-deploy.yml
+++ b/.github/workflows/infra-deploy.yml
@@ -17,9 +17,18 @@ jobs:
           script: |
             set -e
             cd /opt/ASCII-Infra
-            
+
             git pull origin main
-            
-            docker exec nginx nginx -t
-            docker compose up -d
-            docker exec nginx nginx -s reload
+
+            docker run --rm -t -v $(pwd)/nginx_config_path:/etc/nginx/nginx.conf:ro nginx:alpine nginx -t
+
+            docker compose up -d --build
+
+            sleep 5
+            if [ "$(docker inspect -f '{{.State.Running}}' nginx)" != "true" ]; then
+              echo "Nginx failed to start!"
+              docker compose logs nginx
+              exit 1
+            fi
+
+            docker image prune -f
